### ISSUE TITLE
Better automate the data update process

### ISSUE THREAD

**Issue by blahah** [fathomlabs/open-retractions#8]
The initial dataset was generated using a pipeline of command-line tools.

We need a robust script for updating the data and regenerating stats (see #7).

**Comment by XavRsl** [comment]
Hi !

I've been trying to update API data locally but got an error 

```
# node update/daily.js
Getting all CrossRef
Querying CrossRef with: { cursor: '*',
  rows: 1000,
  filter: 'is-update:true,update-type:corrected-article,update-type:correction,update-type:Correction,update-type:correspondence,update-type:corrigendum,update-type:Corrigendum,update-type:err,update-type:erratum,update-type:Erratum,update-type:expression_of_concern,update-type:expression-of-concern,update-type:Removal,update-type:Retraction,update-type:retration,update-type:Withdrawal' }
got record 10.1002/job.1858

Successfully retrieved 1000 entries from CrossRef
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: no writecb in Transform class
    at afterTransform (/Users/roussel/Code/open-retractions/node_modules/readable-stream/lib/_stream_transform.js:74:40)
    at TransformState.afterTransform (/Users/roussel/Code/open-retractions/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at Through2.crossref2retraction [as _transform] (/Users/roussel/Code/open-retractions/node_modules/crossref-to-retraction/index.js:25:5)
    at Through2.Transform._read (/Users/roussel/Code/open-retractions/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Through2.Transform._write (/Users/roussel/Code/open-retractions/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/roussel/Code/open-retractions/node_modules/readable-stream/lib/_stream_writable.js:337:64)
    at writeOrBuffer (/Users/roussel/Code/open-retractions/node_modules/readable-stream/lib/_stream_writable.js:326:5)
    at Through2.Writable.write (/Users/roussel/Code/open-retractions/node_modules/readable-stream/lib/_stream_writable.js:263:11)
    at DestroyableTransform.ondata (/Users/roussel/Code/open-retractions/node_modules/readable-stream/lib/_stream_readable.js:540:20)
    at emitOne (events.js:96:13)
```

Am I doing something wrong ?

Thanks

Xavier
